// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC57KWBUgHtP47ovUhkwKoO4ESYIVTwyPE',
    appId: '1:949992618241:web:0381faded987c009314300',
    messagingSenderId: '949992618241',
    projectId: 'runtime-terror-b31ea',
    authDomain: 'runtime-terror-b31ea.firebaseapp.com',
    storageBucket: 'runtime-terror-b31ea.appspot.com',
    measurementId: 'G-ZP5250XZG6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-jAzK470oyNeOH-Hs4OHS_BJvV3s83uc',
    appId: '1:949992618241:android:517383cd34afd9db314300',
    messagingSenderId: '949992618241',
    projectId: 'runtime-terror-b31ea',
    storageBucket: 'runtime-terror-b31ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYFvXXiNA0ko2i6tSJQSjvPtzNj26bnT4',
    appId: '1:949992618241:ios:c42853cabc16b2af314300',
    messagingSenderId: '949992618241',
    projectId: 'runtime-terror-b31ea',
    storageBucket: 'runtime-terror-b31ea.appspot.com',
    iosClientId: '949992618241-lfr2dctvk5u23o1csot1tpt53hde0138.apps.googleusercontent.com',
    iosBundleId: 'com.example.wayOut',
  );
}
